# Generated by Django 5.1.3 on 2024-11-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(blank=True, help_text='Selecione a Unidade Federal', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='Unidade Federal'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(blank=True, help_text='Selecione o livro', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Selecione o usuário', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Selecione o autor', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(blank=True, help_text='Selecione a editora', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.editora', verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(blank=True, help_text='Selecione o gênero literário', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero Literário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade'),
        ),
    ]
